### ISSUE TITLE
无法收集crash信息

### ISSUE THREAD

**Issue by heyehao2008** [HDB-Li/LLDebugTool#31]
运行demo。触发crash后，再次进入APP，弹出crash report页面，里面是空的。什么数据都没有。
真机iPhone5s ios 11.4测试
xcode9.4.1模拟器测试
如何才能收集到crash信息呢？

**Comment by HDB-Li** [comment]
@heyehao2008  Thanks for your asking.
You need tap this button some times, because Xcode intercept the crash first, It won't call `LLCrashHelper`.   It's okey when you don't running in xcode.   I will try to fix demo as soon as possible.

![1535684275621](https://user-images.githubusercontent.com/28746247/44890475-03849200-ad0d-11e8-83f7-17d6413757c0.jpg)

**Comment by heyehao2008** [comment]
不运行xcode的情况下测试demo。模拟器可以正常收集crash信息，真机还是不行。作者真机测试可以正常收集crash吗？

**Comment by HDB-Li** [comment]
@heyehao2008
Thank you very much, I just fix this bug in version 1.1.6 and push it to master/CocoaPods, you can upgrade.
